export enum ErrorCode {
  // App
  ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
  EMPTY_CART = 'EMPTY_CART',
  INVALID_STATUS_TRANSITION = 'INVALID_STATUS_TRANSITION',
  FORBIDDEN = 'FORBIDDEN',
  VALIDATION = 'VALIDATION',

  // Http
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
