export enum ErrorCode {
  // App
  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
  CATEGORY_IN_USE = 'CATEGORY_IN_USE',
  INSUFFICIENT_STOCK = 'INSUFFICIENT_STOCK',
  FORBIDDEN = 'FORBIDDEN',
  UNAUTHORIZED = 'UNAUTHORIZED',
  VALIDATION = 'VALIDATION',

  // Http
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
