export enum ErrorCode {
  CART_EMPTY = 'CART_EMPTY',
  INVALID_QUANTITY = 'INVALID_QUANTITY',
  ITEM_NOT_IN_CART = 'ITEM_NOT_IN_CART',
  PRODUCT_FETCH_FAILED = 'PRODUCT_FETCH_FAILED',
  VALIDATION = 'VALIDATION',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
