export enum ErrorCode {
  // App
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  EMAIL_ALREADY_IN_USE = 'EMAIL_ALREADY_IN_USE',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  VALIDATION = 'VALIDATION',

  // Http
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
