export enum ErrorCode {
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  EMAIL_ALREADY_IN_USE = 'EMAIL_ALREADY_IN_USE',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
}
